apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasktraverser
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jovanasiljanovska/DevOps-Project.git
    targetRevision: main
    path: TaskTraverser/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tasktraverser
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
