apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tasktraverser
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: your_password_here
  POSTGRES_DB: todotraverse
