apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: tasktraverser
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todo (
    todo_id SERIAL PRIMARY KEY,
    description VARCHAR(30)
    );

